// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RollerPizza.Data;

#nullable disable

namespace RollerPizza.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20220615130042_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RollerPizza.Model.Drink", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<sbyte>("Quantity")
                        .HasColumnType("tinyint(100)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(38,2)");

                    b.HasKey("ID");

                    b.ToTable("Drink", (string)null);
                });

            modelBuilder.Entity("RollerPizza.Model.Pizza", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<sbyte>("Quantity")
                        .HasColumnType("tinyint(100)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(38,2)");

                    b.HasKey("ID");

                    b.ToTable("Pizza", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
